name: spit_hackathon
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  
  email_validator: ^2.1.17
  google_fonts: ^4.0.2
  get: ^4.6.5
  fluttertoast: ^8.1.2
  flutter_switch: ^0.3.2
  shared_preferences: ^2.0.17
  firebase_dynamic_links: ^5.0.11
  url_launcher: ^6.1.8
  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2
  cloud_firestore: ^4.3.1
  flutter_svg: ^1.1.6
  google_sign_in: ^5.4.4
  image_picker: ^0.8.6+1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0
  firebase_analytics: ^10.1.0
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
